version: '3'
services:
  comfyui:
    image: yanwk/comfyui-boot:cu124-megapak
    container_name: comfyui-cu124-mega
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8188:8188"
    volumes:
      - ./storage:/root
    environment:
      - CLI_ARGS=--fast