[settings]
experimental = true

[tools]
node = 'lts'
ruby = '3'
rust = 'latest'
python = '3.12'
bun = 'latest'
fzf = 'latest'
ripgrep = 'latest'
ghq = 'latest'
lazygit = 'latest'
bottom = 'latest'
peco = 'latest'
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
