[settings]
experimental = true
pipx_uvx = true

[tools]
node = "22"
ruby = '3'
rust = 'latest'
python = "3.11"
bun = 'latest'
fzf = 'latest'
ripgrep = 'latest'
ghq = 'latest'
lazygit = 'latest'
bottom = 'latest'
peco = 'latest'
yarn = 'latest'
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:pnpm" = "latest"
uv = "latest"
