---
- name: Install Homebrew
  hosts: localhost
  become: yes
  tasks:
    - name: Install Homebrew using curl and bash
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew  # 既に Homebrew がインストールされている場合はスキップ
      environment:
        NONINTERACTIVE: 1  # 非対話モードで実行