
---
- name: Check if mise is already installed
  ansible.builtin.command:
    cmd: mise --version
  register: mise_installed
  ignore_errors: yes
  changed_when: false

- name: Install mise (if not installed)
  block:
    - name: Install mise using curl and sh
      shell: |
        curl https://mise.run | sh
        
    - name: Run mise install
      shell: |
        mise install -y

  when: mise_installed is failed
