---
- name: Check if HTTPie is already installed
  ansible.builtin.command:
    cmd: http --version
  register: httpie_installed
  ignore_errors: yes
  changed_when: false

- name: Install HTTPie (if not installed)
  block:
    - name: Add HTTPie GPG key
      ansible.builtin.shell:
        cmd: |
          curl -SsL https://packages.httpie.io/deb/KEY.gpg | gpg --dearmor -o /usr/share/keyrings/httpie.gpg
        creates: /usr/share/keyrings/httpie.gpg
      changed_when: false

    - name: Add HTTPie repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./"
        state: present
        filename: httpie.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install HTTPie package
      ansible.builtin.apt:
        name: httpie
        state: latest
        install_recommends: no

  when: httpie_installed is failed  # HTTPieがインストールされていない場合のみ実行