---
- name: Install wslu
  hosts: localhost
  become: yes
  tasks:
    - name: Add PPA for wslu
      apt_repository:
        repo: "ppa:wslutilities/wslu"
        state: present
        update_cache: no  # ここでは手動でapt updateを行うため、noに設定

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install wslu
      apt:
        name: wslu
        state: present
        update_cache: no  # 既に上でupdate_cacheを行っているため、noに設定