- name: Ensure keyrings directory exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Cloudflare GPG key
  get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: '0644'
  become: yes

- name: Add Cloudflare repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main"
    state: present
    filename: cloudflared
  become: yes

- name: Install cloudflared
  apt:
    name: cloudflared
    state: present
    update_cache: yes
  become: yes