---
- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Install Docker
  become: yes
  shell: sh /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker  # Dockerが既にインストールされている場合はスキップ

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start and enable Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes 