- name: Download Miniforge installer
  ansible.builtin.get_url:
    url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"
    dest: "/tmp/miniforge.sh"
    mode: "0755"

- name: Install Miniforge in silent mode
  ansible.builtin.command:
    cmd: "/tmp/miniforge.sh -b -p {{ ansible_env.HOME }}/miniforge3"
    creates: "{{ ansible_env.HOME }}/miniforge3/bin/conda"

- name: Clean up installer
  ansible.builtin.file:
    path: "/tmp/miniforge.sh"
    state: absent

