---
- name: Update apt cache
      apt:
        update_cache: yes

- name: Install curl (if not already installed)
  apt:
    name: curl
    state: present
  when: >
    not ansible_facts.packages['curl'] is defined

- name: Install wget (if not already installed)
  apt:
    name: wget
    state: present
  when: >
    not ansible_facts.packages['wget'] is defined

- name: Install stow (if not already installed)
  apt:
    name: stow
    state: present
  when: >
    not ansible_facts.packages['stow'] is defined
