---
- name: Install common tools on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Include common tools installation tasks
      import_tasks: tasks/common_tools.yml
    - name: Include modern tools installation tasks
      import_tasks: tasks/modern_tools.yml
    - name: Include editor tools installation tasks
      import_tasks: tasks/editor_tools.yml
